### PR TITLE
Moved the mobile and non-mobile URLs into a list of tuples

### PR DESCRIPTION
**Pull request by ghost**
This way adding more websites to make non-mobile is fairly easy.

### CODE REVIEW

**Comment by xl0** [comment]
Hey. Thanks, it looks OK. if you are interested in a real problem, the bot needs edit tracking. Quite often the author would edit the comment to change the link to non-mobile when they see the bot reply. Or sometimes they give a broken link, and edit it later. The bot needs to remove its comments when the original comment no longer has a mobile link, and edit the comment when the original comment is edited.

**Comment by ghost** [comment]
I'll have a look.

If you have any other features/bugs, add them to the issue tracker. If I have time, I may take a look at them.

**Comment by ghost** [comment]
_ahem_ merge pls?

**Comment by xl0** [comment]
Done, sorry.

**Comment by xl0** [comment]
Added the comment tracking issue if you'd like to have a look.

**Pull request merged**
